#!/bin/bash

if [[ $# -gt 0 ]]; then
	ACTION="install"
	case ${1} in
		install)
			ACTION="install"
			shift
		;;
		update)
			ACTION="update"
			shift
		;;
		remove)
			ACTION="remove"
			shift
		;;
	esac

	yum ${ACTION} -y $@
fi

yum clean all
rm -rf /var/cache/yum
